version: '3.9'

services:
  mawster:
    image: ghcr.io/aottr/buncord:latest
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '8'
    volumes:
    - type: bind
      source: ./data
      target: /usr/src/app/data
    env_file:
    - ./.env.local
